export const languages = [
  { value: "cs", label: "Čeština" },
  { value: "da", label: "Dansk" },
  { value: "de", label: "Deutsch" },
  { value: "et", label: "Eesti" },
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
  { value: "fil", label: "Filipino" },
  { value: "fr", label: "Français" },
  { value: "hr", label: "Hrvatski" },
  { value: "id", label: "Indonesia" },
  { value: "it", label: "Italiano" },
  { value: "lv", label: "Latviešu" },
  { value: "lt", label: "Lietuvių" },
  { value: "hu", label: "Magyar" },
  { value: "ms", label: "Melayu" },
  { value: "nl", label: "Nederlands" },
  { value: "no", label: "Norsk" },
  { value: "pl", label: "Polski" },
  { value: "pt", label: "Português" },
  { value: "ro", label: "Română" },
  { value: "sk", label: "Slovenčina" },
  { value: "sl", label: "Slovenščina" },
  { value: "fi", label: "Suomi" },
  { value: "sv", label: "Svenska" },
  { value: "vi", label: "Tiếng Việt" },
  { value: "tr", label: "Türkçe" },
  { value: "el", label: "Ελληνικά" },
  { value: "uk", label: "Українська" },
  { value: "th", label: "ไทย" },
  { value: "ko", label: "한국어" },
] as const;

// 🔥 Automatically infer type from values
export type LanguageCode = typeof languages[number]["value"];