import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik, Roboto as GoogleRoboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { store } from "@/store/index";
import ReduxProvider from "@/store/ReduxProvider";

// Google Fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const rubik = Rubik({ variable: "--font-rubik", subsets: ["latin"] });
const roboto = GoogleRoboto({ variable: "--font-roboto", subsets: ["latin"] });

// Local Fonts

const Poppins = localFont({
  src: [
    { path: "../public/fonts/Poppins-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/Poppins-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../public/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "SmartQr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${Poppins.variable} ${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${rubik.variable}`}
    >
      <body className="antialiased">
        {" "}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
