import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const HelveticaNeue = localFont({
  src: [
    { path: '../public/fonts/HelveticaNeue-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../public/fonts/HelveticaNeue-Medium.ttf', weight: '500', style: 'normal' },
  ],
  variable: '--font-HelveticaNeue',
});

const Poppins = localFont({
  src: [
    { path: '../public/fonts/Poppins-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../public/fonts/Poppins-Medium.ttf', weight: '500', style: 'normal' },
    { path: '../public/fonts/Poppins-SemiBold.ttf', weight: '600', style: 'normal' },
    { path: '../public/fonts/Poppins-Bold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "SmartQr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${Poppins.variable} ${HelveticaNeue.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}